magicmonty/bash-git-prompt

- themes/Single_line.bgptheme
- themes/Single_line_Ubuntu.bgptheme
Single_line_Ubuntu theme addresses problem with corrupted display for multiple fonts (like Terminus and other PowerLine compatible).
> Fix for Single_line theme and a new Single_line_Ubuntu theme.

- themes/Crunch.bgptheme
- themes/Single_line_Solarized.bgptheme
- themes/Solarized_Extravagant.bgptheme
I have corrected the theme names for Crunch and Solarized_Extravagant of the pull request #128
>  Added some more themes.

- gitstatus.sh
This commit fixes the Local Indicator which was broken because of theme related changes.
> [Local Branch Indicator] Change case from No upstream to no upstream

- themes/TruncatedPwd_WindowTitle.bgptheme
This is a custom theme using prompt_callback.
It generates a Debian style prompt with a truncated PWD depending on window width. Also changes the window title to user@host <truncatedPWD>
Fixes issue #155
> Custom theme using prompt_callback

- themes/TruncatedPwd_WindowTitle.bgptheme
Remove trailing whitespaces in the TruncatedPwd_WindowTitle theme
> Remove trailing whitespaces in the TruncatedPwd_WindowTitle theme

- gitprompt.sh
Some functions had indent set to 4 spaces while the majority had 2. Changed all functions to have the same indentation.
Since check if prompt_callback is a function is run every time you press enter, I changed it to a bit quicker test than type -t.
> Re-indented functions. Added faster check for function type.

- gitstatus.sh
First stab at fixing the parsing of branches containing dots in the name
Needs some testing.
@pedantic79
> Possible to have dots in branch name

- gitprompt.sh
Honors VIRTUAL_ENV_DISABLE_PROMPT used by virtual env.
> Duplicated code moved to helper function

- themes/Single_line_Ubuntu.bgptheme
A fix to address latest changes.
> Fix for Single_line_Ubuntu.bgptheme

- themes/Crunch.bgptheme
- themes/Custom.bgptemplate
- themes/Default.bgptheme
- themes/Single_line.bgptheme
- themes/Single_line_Solarized.bgptheme
- themes/Single_line_Ubuntu.bgptheme
- themes/Solarized_Extravagant.bgptheme
Made a pass through all themes and added the new UPSTREAM variable where applicable, except for the one already in another PR.
> Cleanup of themes, adding the new upstream variables where applicable

- themes/Default.bgptheme
- themes/TruncatedPwd_WindowTitle.bgptheme
- themes/TruncatedPwd_WindowTitle_NoExitState.bgptheme
- themes/TruncatedPwd_WindowTitle_NoExitState_Ubuntu.bgptheme
- themes/TruncatedPwd_WindowTitle_Ubuntu.bgptheme
According to
http://stackoverflow.com/a/13864829
this is one way of getting test to distinguish between not set and set to empty string. I've tested it on Ubuntu, OS X and Cygwin.
Also, updated my themes to take advantage of the fact that the empty string can be counted as a set value.
> Change test to accept empty string as set

- gitstatus_pre-1.7.10.sh
Checked in the wrong version on the file. in #239.
> Fixed typo

- gitprompt.sh
I think this will solve the problem for old bash versions
> Solves issue #252: error message in prompt with old bash version

- README.md
- gitprompt.sh
#![screenshot_2016-07-15-16h_00m_56s](https://cloud.githubusercontent.com/assets/17233561/16876773/901f1630-4aa5-11e6-9e28-a5c4dbed1708.png)
Toggle gitprompt by running "git_prompt_toggle" in bash:
$ git_prompt_toggle
> Toggle gitprompt

- gitstatus.py
Hi,
i had some problems with the ahead unicode symbol...
py3 was also not working correct
> fix utf8 and python3

- themes/Minimal.bgptheme
Hi,
Here is a new theme for users who do not need to remind who they are, neither where their GIT projects are, nor on which machine they work :)
Hope you will like it !
> Minimal theme based on TruncatedPwd_WindowTitle

- themes/Plague_Doctor.bgptheme
A new theme for you. Hope you like it.
Cheers,
P.D.
> Plague Doctor's theme

- themes/Minimal_Switch.bgptheme
- themes/Minimal_UserHost.bgptheme
I added a theme based on Minimal with User@Host on the second line
> Minimal_UserHost theme

- README.md
- gitprompt.fish
Updated README with steps I used to integrate with the web GUI and added description and author comment to fish file.
> Added instructions for using with fish_config

- themes/Single_line_NoExitState_Gentoo.bgptheme
This one is a simple Theme for Single-Line Prompt without Exit State on the Base of default Gentoo Prompt.
> Single Line Theme for Gentoo Prompt without Exit State

- README.md
This update makes it a one-line `git clone` command & makes it better looking in the ~/.bashrc file.
> DOC: update installation/configuration instructions

- themes/Minimal_Chevron.bgptheme
> Derived from Minimal theme.

- README.md
> README: remove spaces that increase horisontal scroll

- themes/Solarized_UserHost.bgptheme
- themes/Windows_UserHost.bgptheme
I made some improvements to the theme I submitted some years ago, Solarized_UserHost.
Also as I mentioned in #296, I am submitting the theme I made for PowerShell posh-git, I called it Windows_UserHost.
> Fixes for Solarized_UserHost and new theme Windows_UserHost

- gitprompt.sh
Reverts magicmonty/bash-git-prompt#477 due to a regrssion (magicmonty/bash-git-prompt#506)
> Revert "Replace while read loop with a readarray"

- themes/Minimal_Chevron.bgptheme
color reload was using Minimal_Time instead of unique value.
> Minimal chevron theme reload patch

- README.md
- gitprompt.sh
Add ability to place virtual environment infos between prompt and git status (instead of left to the prompt).
> Make venv position configurable.

- themes/Multi_line_NoExitState_Gentoo.bgptheme
The longer the directory structure, the more convenient and useful is a new-line.
> Add Custom Theme: Multi Line without Exit State like default Gentoo bashprompt

- themes/Single_line_Minimalist_robbyrussell.bgptheme
- themes/Single_line_Minimalist_robbyrussell_kube-ps1.bgptheme
I added two themes: 
- robbyrussell 
- robbyrussell + kube-ps1
https://github.com/ohmyzsh/ohmyzsh/wiki/Themes#robbyrussell
https://github.com/jonmosco/kube-ps1
> Add custom themes

- themes/Solarized_UserHost.bgptheme
- Fix #526 `root` user unset ResetColor
> FIX: Solarized_UserHost.bgptheme unset ResetColor
