- gitstatus.sh
Problem: the indicator for untracked files is not working correctly if you are in a subdirectory of the repository.
Pass the repository root to git ls-files (obtained via rev-parse --show-cdup) so that it shows *all* untracked files in the repository, instead of just untracked files in the working directory.
> Show all untracked files in the repository instead of just from ./ on

- themes/Single_line_NoExitState_openSUSE.bgptheme
- themes/Single_line_openSUSE.bgptheme
Hi,
I tried `bash-git-prompt` in openSUSE distribution, works nice, but the default theme is too different to the standard openSUSE bash prompt style.
I found out that defining a new style is really easy so I created two styles which mimic the default openSUSE prompt style.
Thank you!
> Added openSUSE themes

- gitprompt.sh
Paths with spaces in `$__GIT_PROMPT_DIR` are preventing themes from being loaded correctly.
> use double quotes to handle path with spaces

- gitprompt.sh
Found myself wandering which signal exit status 141 was, and after toying with the arithmetic to discover it was signal 13 then had to look up the symbolic name for this to discover it was SIGPIPE. Figured it would be nice if the prompt that showed me the number did the leg work for me.
As it happens, the BASH builtin `kill` can actually translate a number into a symbolic name natively, which means this patch should be portable between Linux / BSD / OSX where signal numbers may vary. My testing on OSX (10.10) and Linux (3.2) has shown it to be useful and, thus far, correct.
> _LAST_COMMAND_INDICATOR_ now displays symbolic names of signals

- git-prompt-help.sh
unless called from the bash-git-prompt directory.  Fixed by adding "{__GIT_PROMPT_DIR}/".
(This pull request replaces #131, where I pushed a second change while there was a pending pull request.)
> get_prompt_help() failed sourcing themes/Default.bgptheme,

- gitprompt.sh
- themes/Crunch.bgptheme
- themes/Solarized_Extravagant.bgptheme
Add a workaround for the lack of -mmin in Solarises find, check for
gfind from opencsw and failing that use perl, which Solaris ships with
and is widely available on many other systems.
Use eval in async_run to run the command, the old bash in Solaris 5.10
does not recognize the previous syntax.
Use command -v instead of which to check for the existance of rbenv in
the Crunch and Solarized_Extravagant themes. command -v is the POSIX-ly
correct way to check for the existance of a command, and which does not
set the exit code on Solaris.
> Fix Solaris compatibility

- bash-git-prompt.spec
The spec file needed the install *.py line to be commented out in order to work.
> Spec file tried to include non-existent python files

- git-prompt-help.sh
Seems to me the help output should use the GIT_PROMPT_ variables across the output
> Help strings should use the themed variables

- gitstatus.sh
Use symbolic-ref --short to get the branch name without the refs/heads
Signed-off-by: Roy Golan <rgolan@redhat.com>
> Simplify branch name extraction

- gitprompt.sh
bash-git-prompt did not work for me on ubuntu while it does work on osx. The reason seems to be that in interactive shells, ls is aliased to ls --colors on ubuntu. This causes the matching for themes to fail.
This patch fixes that problem by changing how the matching works.
> fix match for theme

- README.md
Change .bashrc to .bash_profile since it is the standard file to use for startup w/ latest OS-X.
Also Atom editor removed the white space at end of sentences. That's what the rest of those changes are in the file. Hope that isn't an issue.
Cheers
> Extremelly minor change to installation README.md for OS-X.

- gitstatus.py
- gitstatus.sh
Improve performance of gitstatus.sh/py. This removes a bunch of calls to git and replaces them with one using `git status --porcelain --branch`. Based off of changes by @wkentaro to zsh-git-prompt (see: https://github.com/olivierverdier/zsh-git-prompt/pull/65)
Also, removed a call to `git stash list` and look directly at the logs file that contains that information. Since we just need the number this is much faster than actually going through and having `git stash list` parse the log information before spitting it out.
> Use `git status --porcelain --branch` to improve performance

- gitstatus.sh
This removes the need to use `wc -l` to count the number of lines of the stash file. We can read files one line at a time, so we can just use that.
> Remove calling wc to count lines.

- gitprompt.sh
Listing themes and matching themes used cd, ls and echo.
I replaced with standard bash parameter substitution.
Speedup is a factor 10x on cygwin.
@pedantic79 could you have a look and see if this looks OK?
> Theme listing optimized using bash parameter substitution

- gitstatus.py
Changed python version to behave like the refactored gitstatus.sh:
* Same order of ahead/behind
* Same logic for extracting tag or hash
* Fixed all Python warnings and indentation
What differs is that the python version expands the symbols directly in the result instead of the placeholders found in gitstatus.sh (e.g. _AHEAD_, _BEHIND_)
On a local branch we get _NO_REMOTE_TRACKING_ as remote name in the bash version and dot ('.') in the python version. 
I don't know if anything actually uses the python version, if so it really should be changed to behave exactly like the bash version, but that requires more knowledge about the usage of gitstatus.py.
> Python cleanup

- gitstatus.sh
The old version of gitstatus.sh counted all untracked files, even in subdirectories. This patch makes the new one behave like the old one, i.e. shows all untracked file count.
> Fixed bug where not all untracked files in folders were shown

- git-prompt-help.sh
- gitprompt.sh
- gitstatus.sh
- gitstatus_pre-1.7.10.sh
Had hard time to make bash-git-prompt work with nixos where bash is not in /bin/bash. This was enough to make prompt work.
> Use portable shebang

- gitstatus_pre-1.7.10.sh
eliminating an extra git command if no upstream branch is found
> Simplified old gitstatus

- themes/Single_line.bgptheme
- themes/Single_line_Solarized.bgptheme
The new variables introduced are checked for in define_undefined_git_prompt_colors, and Two themes remain that override that function.
> Themes overriding define_undefined_git_prompt_colors needs the new variables

- themes/Default.bgptheme
I had a problem that I could not set `GIT_PROMPT_COMMAND_OK=''`. Fixed the problem with this.
> Use `test -v` to allow overriding defaults with empty strings

- gitprompt.sh
As far as I can see these local variables are not used. If not, they should be removed.
> Removed unused variables

- themes/Single_line_NoExitState.bgptheme
- themes/Single_line_Solarized.bgptheme
- themes/Single_line_Ubuntu.bgptheme
A few themes were a copy of the default theme instead of overriding the variables needed setting.
To avoid the `test -z` problem for all of them, I refactored them to override Default instead.
I did a diff using
```sh
set |egrep "^GIT_PROMPT_*"
```
To make sure that all variables are set equally between the old and new version.
> Changed the themes to properly override Default theme

- README.md
- gitstatus.sh
I am working via sshfs on a large repository which mixes source files with build artifacts. Hence I get potentially lots and lots of untracked files. Sometimes the git status takes 5 minutes to complete, if the connection is bad. I also do not need this information. 
So I made the parameter for git status --untracked-files configurable. There is now a new environment variable, called GIT_SHOW_UNTRACKED_FILES, which if set is passed to git status. If it is not set, default behaviour of "all" will apply. Setting it to "no" or "normal" will speed things up a lot.
> Make counting ALL untracked files optional

- README.md
Otherwise it would be more correct to say file(s) with merge conflict(s).
> Fix plurality in README

- gitstatus.sh
- gitstatus_pre-1.7.10.sh
The conflicts flag is not taken into account for the *computation* of the `clean` flag when using `gitstatus.sh` and `gitstatus_pre-1.7.10.sh`. However it is in the python version `gitstatus.py`.
In case your git working tree has nothing that make it *dirty* but conflicts, the prompt shows a wrong `clean` flag alongside the correct `conflict`:
While reporting this fix into the `gitstatus_pre-1.7.10.sh` as well, I noticed that the `num_U` variable was not set nowhere. So I deleted it.
> Take conflicts into account for 'clean' flag

- gitstatus.sh
I guess thare is a typo here, since gitstatus_pre-1.7.10.sh checks against 0.
> check num_conflicts against 0

- gitstatus.sh
When working tree is at a detached head and that commit id has a tag, currently we only show it when the tag is annotated, even if an unannotated tag is available.  Adding the --tags flag to git-describe will let it fall back to choosing an unannotated tag if there is no annotated tag.  If neither kind of tag exists for this commit id, a short SHA1 hash is still returned.  Since a lot of git repos use unannotated tags (including this one), this change should make the bash-git-prompt a little more friendly for users who are looking at a historical point in time.
This has been tested with git 1.9.1 and 2.5.0 with equivalent results.
Attached is a short shell script demonstrating the behavior on a toy git repo:
[example.sh.txt](https://github.com/magicmonty/bash-git-prompt/files/190269/exampl …
> Show an unannotated tag too

- gitstatus_pre-1.7.10.sh
If pr #238 is merged, this should make legacy Git work the same way. I ran the provided script from #238 as well:
```
Show git version, for the record.
git version 1.7.9.5
Creating toy git repo.
Making a few commits and tagging them.
Checking out unannotated tag 'unannotated-tag-1'.
By default, we cannot find this commit's tag unless it is annotated.
fatal: no tag exactly matches '7dfb6ae84369269e36618b2011c71579fec7c0a1'
With the --tags flag, we can also find an annotated flag.
unannotated-tag-1
Adding a more unannotated tags to the same commit id.  The tag that sorts first (using locale-specific sort order) is shown.
aaa-alphabetically-first-unannotated-tag
Adding an annotated tag.  Even with the --tags flag, git-describe prefers to return an annotated tag rather than any unannotated …
```
> Make pr#238 work for legacy git as well

- themes/Solarized_UserHost.bgptheme
This theme is based on Solarized_Extravagant, with the ruby prompt, date
and kernel version removed, and user@host added on the second line.
> new theme Solarized_UserHost

- gitprompt.sh
- gitstatus.sh
(1) Deleted items were incorrectly counted as staged
(2) A ResetColor string after the last_command_indicator makes the command line colors be a bit more predictable.
> fix deleted item count and fix last_command_indicator coloring

- gitprompt.sh
The current code for updating the terminal title doesn't properly escape the unprintable characters, leading to line-wrap issues in terminals.
> fix escapes for terminal title

- git-prompt-help.sh
Made 'x' a local variable so the 'git_prompt_color_samples' command can be repeated.
See issue #250.
> Fix repeated 'git_prompt_color_samples' bug

- themes/Evermeet.bgptheme
- themes/Evermeet_Lowres.bgptheme
- themes/Evermeet_Ubuntu.bgptheme
- themes/Evermeet_lowres_screens.bgptheme
I've created 2 theme files, because on low resolution screens, unicode characters might overlap with the following character. Thus there has to be an extra space after the unicode character.
For high res (retina) screens (which are more and more the standard these days) an extra space looks very unprofessional.
> Evermeet theme

- gitprompt.sh
If the user has 
`GIT_PROMPT_ONLY_IN_REPO=1`
the color definitions will not get loaded and
`git_prompt_list_themes` will not show any colors.
I broke out the color loading to a separate function, and call it from the list themes function as well.
Should fix #258
> Extract color definition loading as a function

- gitstatus.sh
A file can be staged AND unstaged at the same time, eg, MM.
Fix is only for git >= 1.7.10
> Fix count for files being staged, unstaged at the same time

- gitstatus.sh
-  operator ;;& replaced to keep bash-3.2 compatibility
- support all status combinations described in manpage of git-status
> Fix count for files being staged, unstaged at the same time, second version

- gitprompt.sh
If git commands run simultaneously on the same repository, one of it might fail because of an locked index. This is e.g. extremly annoying during a long lasting rebase. (In one terminal you run the rebase. Just switching to the same git working directory in another terminal might be enough to make the rebase fail - because "bash-git-promt" fetches the information from "git status" which in turn tries to lock the index file for a short moment)
This pull request circumvents this by introducing a private index file. This is done by using a copy of the real index file. While this bears the risk (also quite unlikely) of a broken index copy, it will only affect "bash-git-prompt" and not the real stuff.
One example of this problem is documented here: …
> Fix index lock issue

- gitstatus.sh
This commit solves the error descibed in #277.
Older versions of bash do not allow negative length values.
> fixes #277, substring expression < 0 issue for older bash versions

- README.md
- gitprompt.sh
In #279 there was a question whether you could disable the number of changed files and leave only the icons.
This pr should apply that feature.
To disable the numbers you set
`GIT_PROMPT_SHOW_CHANGED_FILES_COUNT=0`
before sourcing gitprompt.sh
> Possible to not print the number of changed files

- gitstatus.sh
This lets you run gitstatus.sh without the variable set, this is useful if you are debugging and just want to check the output of gitstatus.sh.
> Fix gitstatus.sh to produce output when ran standalone

- README.md
GIT_PROMPT_ONLY_IN_REPO=1 must be done before gitprompt.sh is loaded, as described in the next section.
> Fix order of commands for the .bashrc

- gitprompt.sh
The approach is to wait with evaluation of the parts that contain the branch names until PS1 is rendered.
This patch handles both the ordinary branch name as well as the upstream branch name.
Try to fix #310.
Credits to @chmike and @jayrhynas
Steps to reproduce the bug and see if the fix works:
```sh
git clone https://github.com/njhartwell/pw3nage.git
cd pw3nage
GIT_PROMPT_SHOW_UPSTREAM=1
unset GIT_PROMPT_SHOW_UPSTREAM
```
Expected result when fixed without upstream info:
```sh
[$(./pw3n)|✔] ✔
```
With upstream info:
```sh
[$(./pw3n) {origin/$(./pw3n)}|✔] ✔
```
> [security] Fix for #310

- gitstatus.sh
* Previously status was also displayed, when branch name contained 'ahead' or 'behind'
> Ahead/Behind only if actually ahead/behind

- README.md
- gitprompt.sh
If length is passed as a parameter, the given length will be used to truncate the pwd. If nothing is specified it defaults to 1/3 of the terminal width.
This enables themes (including mine) to more effectively use the available terminal width.
> extend gp_truncate_pwd to accept parameter with max pwd length

- gitprompt.sh
Try to fix #324.
Let the `.bash-git-rc`-file only contain variable declarations on the form
`^(FETCH_REMOTE_STATUS|GIT_PROMPT_SHOW_UNTRACKED_FILES|GIT_PROMPT_IGNORE)=[0-9a-z]+$`
E.g `FETCH_REMOTE_STATUS=0`
`GIT_PROMPT_SHOW_UNTRACKED_FILES=all`
> [security] Check the syntax of .bash-git-rc before sourcing it

- themes/Single_line_Solarized.bgptheme
this commit updates Single_line_Solarized.bgptheme to reset the root prompt color at the end of the prompt string
before this commit, the root prompt would not reset the terminal text color so it would remain red.
The reason for this change is that having all output in red, makes it harder to sport error messages in  applications that use colors to highlight status
> change root prompt to reset color at the end on Single_line_Solarized

- themes/Chmike.bgptheme
reload_git_prompt_colors used 'Crunch' instead of 'Chmike'. This fixes it.
> Fixed Chmike reload call

- gitprompt.sh
- gitstatus.py
- gitstatus.sh
When `GIT_PROMPT_CLEAN=""`, it leads to a dangling separator at the end when the state is clean.
The commit fixes that by adding the separator only when something will follow after it.
> Git 2.14 compatibility. Also add separator to status only if something follows it

- themes/Single_line_Dark.bgptheme
I wrote a theme used by a dozen of persons, it can be useful for others.
> Add  Single_line_Dark.bgptheme theme

- gitprompt.sh
- themes/Chmike.bgptheme
- themes/Custom.bgptemplate
- themes/Default.bgptheme
- themes/Evermeet.bgptheme
- themes/Evermeet_Lowres.bgptheme
- themes/Evermeet_Ubuntu.bgptheme
- themes/Minimal.bgptheme
- themes/Minimal_UserHost.bgptheme
- themes/Single_line_Dark.bgptheme
- themes/Single_line_NoExitState_Gentoo.bgptheme
- themes/Single_line_NoExitState_openSUSE.bgptheme
- themes/Single_line_openSUSE.bgptheme
- add `$GIT_PROMPT_MASTER_BRANCH` - color for master branch
- add `$GIT_PROMPT_MASTER_BRANCHES` - branch name(s) that use $GIT_PROMPT_MASTER_BRANCH color, 'master' by default)
All other branches will continue to use $GIT_PROMPT_BRANCH
Also add $GIT_PROMPT_MASTER_BRANCH to all themes that set $GIT_PROMPT_BRANCH, using the same color as $GIT_PROMPT_BRANCH to avoid unintended changes.
Fixes https://github.com/magicmonty/bash-git-prompt/issues/311
> Allow different color for master branch

- themes/Single_line_Solarized_Lamda.bgptheme
> Add new theme 1row solarized lamda

- gitprompt.sh
When GIT_PROMPT_FETCH_REMOTE_STATUS is nonzero, suppresses useless password prompts in the terminal created by the remote status failing to be updated. Does not suppress pop-up password prompts outside the terminal
Addresses magicmonty/bash-git-prompt#354
> Suppress fetch password prompt

- gitprompt.sh
I use PROMPT_COMMAND for a custom prompt of my own and this code clobbers my prompt.  In my efforts to isolate the parts I want I ran across this issue which smells like a bug.
> return right away so a success looks like "1" instead of "1 0"

- .gitattributes
When git cloning on linux with `core.autocrlf = true` everything now works as expected.
See #345
> Adds .gitattributes to keep unix lines endings in .sh files; closes #345

- bash-git-prompt.spec
1. Adding comments after %build as building is not
required in this case
2. Putting the %post and %postun sections after %clean
3. Adding to the %changelog
4. Removing clean as it is not recommended during the Fedora Packaging Process
> Making the SPEC file more standards compliant

- gitprompt.sh
This fixes an obscure error that occurs when the original $PROMPT_COMMAND contains new lines
For example if original $PROMPT_COMMAND is:
```
__bp_trap_string="$(trap -p DEBUG)"
trap DEBUG
__bp_install
```
this then results to the prompt var being set to:
```
setLastCommandState; __bp_trap_string="$(trap -p DEBUG)" trap DEBUG __bp_install ;setGitPrompt
```
which then blows up during `eval` with obscure:
```
bash: PROMPT_COMMAND: line 4: syntax error near unexpected token `;'
bash: PROMPT_COMMAND: line 4: `;setGitPrompt'
```
> support new lines in original $PROMPT_COMMAND

- gitprompt.sh
If user has aliased `cd` command gitprompt.sh can break. This forces bash to use the builtin version of cd.
> Changed `cd` to `command cd` to force use of bash builtin cd command

- bash-git-prompt.spec
`install -d` does not take a set of access settings as first numerical argument. At least on MacOS (BSD), but according to [the manpage](https://linux.die.net/man/1/install) also on Linux, an extra directory with the name **`755`** was created. Although `755` is the default value for `install -d`, just for symmetry option `-m 755` is added.
> Fix directory permissions.

- gitprompt.sh
This change allows the user to avoid any signs for missing remote tracking by allowing an empty variable (GIT_PROMPT_SYMBOLS_NO_REMOTE_TRACKING="").
> Allow empty GIT_PROMPT_SYMBOLS_NO_REMOTE_TRACKING variable

- README.md
Added GIT_PROMPT_ONLY_IN_REPO=1 to the Homebrew installation instructions. I'm not sure why this wasn't already in here when the other installation instructions have it. It's annoying to always have Git Prompt active when you're not inside a repo.
> Homebrew installation instructions update

- gitstatus_pre-1.7.10.sh
The new feature with remote username changed the output of gitstatus.sh users running older git (pre 1.7.10) need to use the gitstatus_pre1.7.10.sh instead.
I updated it to hopefully work the same way.
Tested on my Centos 6 installation.
Maybe @stas00 can take a look at this?
> Update old gitstatus to support remote username

- README.md
This addition can be useful for the case when the `~/.bashrc` file with the configuration for using bash-git-prompt was copied over to a machine where `~/.bash-git-prompt` directory is not available, so it does not throw errors immediately on loading.
> DOC: make sourcing conditional in README.md instructions

- gitstatus.sh
Explanation:
For some reason there's a trailing space, when there are changes available on the remote:
`master {upstream/master } ↓·9|✔]$`
After doing a `git pull`, the prompt is fine again:
`master {upstream/master}|✔]$`
This change trims the upstream var in gitstatus.sh
closes #452
> fixes a trailing space in upstream when remote changes available

- gitstatus.sh
Might be a fix for #461 and/or #351
> Use --no-optional-locks in gitstatus.sh to speed up prompt in large repositories

- themes/Custom.bgptemplate
Removed a duplicate `_LAST_COMMAND_INDICATOR_` in the `GIT_PROMPT_START_ROOT` line of `Custom.bgptemplate`.
> Removed duplicate _LAST_COMMAND_INDICATOR_

- gitprompt.sh
My `$WORK` has a [TMOUT](https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html#index-TMOUT) policy for its shell logins, and I was noticing that when using this prompt the session was staying logged in, way past the time allowed!
I'm not sure what is going on to make bash think the `read` is still happening to make the TMOUT effect not work.  But replacing the `while read` loop with `readarray` - the latter being the preferred way, I've found, to read lines from a file -  fixed the issue.
> Replace while read loop with a readarray

- gitstatus.py
Currently, the call to `subprocess.Popen()` only passes `LC_ALL` to the child process. As a result, git will ignore the user-specified global .gitignore file and report untracked files incorrectly.
Alternatively, the child process could inherit all environment variables and then override `LC_ALL`.
> Add HOME environment variable to git status call

- gitprompt.sh
If any script saved in PROMPT_COMMAND wants to know last command exit status (without using GIT_PROMPT_LAST_COMMAND_STATE, but based on "$?" shell variable) after installing bash-git-prompt it stopped working, because "$?" variable was set to success after assigning GIT_PROMPT_LAST_COMMAND_STATE variable.
This PR fixes it.
Reopening again PR #457 under new name, as need `master` branch in my forked repository :-)
> Allow to coexist other PROMPT_COMMAND(s) relying on command exit status

- gitprompt.sh
This PR adds a config option (`GIT_PROMPT_SHOW_TRACKING`, default: `1`) to show/hide tracking info in the CLI prompt.
> Add option to hide tracking info

- git-prompt-help.sh
Additional fix when `${GIT_PROMPT_PREFIX}` or `${GIT_PROMPT_SUFFIX}`
contain color sequences git_prompt_help's formatting was wrong
> Enhance git_prompt_help and example with real colors and markers

- gitprompt.sh
- gitstatus.sh
Private index was tried to create in non-existent location, no error
was ever displayed, and then unconditionally GIT_INDEX_FILE variable
was set pointing to non-existent path. Git used this location and
reported many changed files.
Additionally in case of non-existent index file most of
files were marked with `D` in second loop pass of `gitstatus.sh`
which was wrongly identified as 'Stashed'.
It is common on Android devices - there is no /tmp directory
Termux creates one and sets `TMPDIR` variable, which is commonly
honoured by most of unix utilities.
> Fix issue #338 - Fixes behaviour if `/tmp` dir does not exist

- themes/BlackOrWhite.bgptheme
I'm using a modified bash prompt to show git branch in the prompt, but special git informations were missing. When I found your awesome project I decided that I would like to use it. So I created a new theme with that prompt what I'm using and I thought if I already worked on it then I would like to share with you.
> Add new theme BlackOrWhite

- git-prompt-help.sh
- gitprompt.sh
- gitstatus.sh
- prompt-colors.sh
- tests/test-non-git-ps1.sh
- themes/Default.bgptheme
This is a continuation of #469 by @geksiong, since I haven't heard from the original author in a few years (https://github.com/geksiong/bash-git-prompt/pull/2). These changes have been confirmed to work on both zsh and bash, but not fish.
> Add support for zsh

- git-prompt-help.sh
- gitprompt.sh
- gitstatus.sh
- gitstatus_pre-1.7.10.sh
- Replace deprecated backticks with $()
- Replace use of deprecated `egrep` with `grep -E`
- Disable ShellCheck false positive
- Every single use of `gp_set_window_title` has 1 positional parameter, so only interpolate `$1`
This is a good project, and I noticed that there were several issues that have already been fixed, or are old enough that they are not relevant (uses an EOL Linux Distribution). I have marked the following as to close. There are more, but I think this is a good start. Closing these old issues makes the repository seem more maintained, and it's easier to triage and look for existing issues when they are closed.
Closes #420 (stale, not enough information)
Closes #327 (stale, fixed on later Debian version)
Closes #225 (stale, fixed on later Ubuntu version)
Closes #347 …
> Fix minor ShellCheck violations

- README.md
There were inconsistencies that I have addresses in these improvements to the README.
This additionally closes (Closing these old issues makes the repository seem more maintained, and it's easier to triage and look for existing issues when they are closed.):
- Closes #212 (fixed by 5b7c0672702956f854d2909f521eee90e11f78d8)
- Closes #362 (fixed by 5b7c0672702956f854d2909f521eee90e11f78d8)
- Closes #256 (fixed by #254)
- Closes #358 (stale, question addressed)
- Closes #435 (stale, question addressed)
> readme: Cleanup inconsistent spacing and syntax

- gitprompt.sh
/fixes #539 
The issue seems to be caused by the logic here:
https://github.com/magicmonty/bash-git-prompt/blob/51080c22b2cebb63111379f4eacd22cda199684b/gitprompt.sh#L249-L272
Basically, the values of both `PROMPT_START` and `PROMPT_END` are being set accordingly when entering a git repository, but never being reset to their original values upon exiting.  
This PR adds a couple lines to capture the original values of `PROMPT_START` and `PROMPT_END` on the way in and then resets the values accordingly on the way out.
> Resetting PROMPT_START/PROMPT_END on exit

- gitprompt.sh
It's possible to specify the prompt to be used for a venv, and if that is set, prefer that over the basename of the venv directory.
> Use prompt from venv, if set

- README.md
As otherwise `rpmbuild` barfs (at least on Fedora 40)
> RPM build instructions: ensure LICENSE.txt included in tarball
